// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::{
    fs::File,
    io::{BufReader, Cursor},
    path::PathBuf,
};

use num_bigint::BigInt;
use reference::{
    algebra::{Field, Gf2_128, P256, Rng},
    circuit::{compute_circuit_id, parse_lfc2_bytes},
    ligero::LigeroConfig,
    zk::{ZkProver, ZkVerifier, read_zk_proof, write_zk_proof},
};

pub struct SimpleRng {
    pub state: u64,
}

impl SimpleRng {
    pub fn new(seed: u64) -> Self {
        Self { state: seed }
    }
}

impl Rng for SimpleRng {
    fn bytes(&mut self, len: usize) -> Vec<u8> {
        let mut out = Vec::with_capacity(len);
        let mut state = self.state;
        for _ in 0..len {
            state = state
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            out.push(((state >> 32) & 0xff) as u8);
        }
        self.state = state;
        out
    }
}

fn get_testdata_path(relative_path: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative_path)
}

fn run_reference_test_helper<F: Field + 'static>(
    circuit_path: &str,
    inputs_path: &str,
    expected_proof_path: &str,
    config: LigeroConfig,
    seed: u64,
    label: &str,
    parse_input_fn: impl Fn(&str) -> F,
) {
    let circuit_full_path = get_testdata_path(circuit_path);
    let inputs_full_path = get_testdata_path(inputs_path);
    let expected_proof_full_path = get_testdata_path(expected_proof_path);

    // 1. Load Circuit
    let circuit_file = File::open(&circuit_full_path).expect("Failed to open circuit file");
    let mut circuit_reader = BufReader::new(circuit_file);
    let circuit_data =
        parse_lfc2_bytes::<F, _>(&mut circuit_reader).expect("Failed to parse LFC2 circuit");

    // 2. Load Inputs
    let inputs_file = File::open(&inputs_full_path).expect("Failed to open inputs file");
    let raw_inputs: Vec<String> =
        serde_json::from_reader(inputs_file).expect("Failed to parse inputs JSON");
    let inputs: Vec<F> = raw_inputs.iter().map(|s| parse_input_fn(s)).collect();

    // 3. Prover commit & prove
    let mut rng = SimpleRng::new(seed);
    let prover = ZkProver::new(circuit_data.clone(), config.clone());
    let commit = prover.commit(&inputs, &mut rng);
    let proof = prover.prove(&inputs, &commit, label);

    // 4. Compare generated bytes with expected bytes
    let sf = F::Subfield::default();
    let mut generated_bytes = Vec::new();
    write_zk_proof(&mut generated_bytes, &proof, &sf).unwrap();

    let expected_bytes =
        std::fs::read(&expected_proof_full_path).expect("Failed to read expected proof");
    assert_eq!(
        generated_bytes, expected_bytes,
        "Proof byte-for-byte mismatch!"
    );

    // 5. Verify the generated proof using ZkVerifier
    let verifier = ZkVerifier::new(circuit_data, config.clone());
    verifier
        .verify(&inputs[0..prover.circuit_data.npublic_input], &proof, label)
        .expect("ZkVerifier failed to verify the generated proof!");

    // 6. Verify the expected proof using ZkVerifier
    let mut expected_reader = Cursor::new(&expected_bytes);
    let expected_proof =
        read_zk_proof(&mut expected_reader, &prover.circuit_data, &sf, &config).unwrap();
    verifier
        .verify(
            &inputs[0..prover.circuit_data.npublic_input],
            &expected_proof,
            label,
        )
        .expect("ZkVerifier failed to verify the expected proof!");
}

#[test]
fn test_reference_sha256() {
    let parse_gf2_128 = |s: &str| {
        let val = BigInt::parse_bytes(s.as_bytes(), 10).unwrap();
        let mut v_bytes = val.to_bytes_le().1;
        v_bytes.resize(16, 0);
        Gf2_128::from_bytes(&v_bytes).unwrap()
    };
    let config = LigeroConfig {
        rate_inv: 3,
        num_queries: 16,
        encoded_len: 256,
    };
    run_reference_test_helper(
        "tests/testdata/sha256_circuit.lfc2",
        "tests/testdata/sha256_inputs.json",
        "tests/testdata/sha256_proof.bin",
        config,
        12345,
        "sha256_spec_test",
        parse_gf2_128,
    );
}

#[test]
fn test_reference_ecdsa2() {
    let parse_p256 = |s: &str| {
        let val = BigInt::parse_bytes(s.as_bytes(), 10).unwrap();
        P256::new(val)
    };
    let config = LigeroConfig {
        rate_inv: 4,
        num_queries: 16,
        encoded_len: 256,
    };
    run_reference_test_helper(
        "tests/testdata/ecdsa2_circuit.lfc2",
        "tests/testdata/ecdsa2_inputs.json",
        "tests/testdata/ecdsa2_proof.bin",
        config,
        123456789,
        "ecdsa2_spec_test",
        parse_p256,
    );
}

#[test]
fn test_reference_security_bounds_validation() {
    let parse_gf2_128 = |s: &str| {
        let val = BigInt::parse_bytes(s.as_bytes(), 10).unwrap();
        let mut v_bytes = val.to_bytes_le().1;
        v_bytes.resize(16, 0);
        Gf2_128::from_bytes(&v_bytes).unwrap()
    };

    let config = LigeroConfig {
        rate_inv: 3,
        num_queries: 16,
        encoded_len: 256,
    };

    // 1. Load Circuit
    let circuit_file = File::open(get_testdata_path("tests/testdata/sha256_circuit.lfc2"))
        .expect("Failed to open circuit file");
    let mut circuit_reader = BufReader::new(circuit_file);
    let circuit_data =
        parse_lfc2_bytes::<Gf2_128, _>(&mut circuit_reader).expect("Failed to parse LFC2 circuit");

    // 2. Load Inputs
    let inputs_file = File::open(get_testdata_path("tests/testdata/sha256_inputs.json"))
        .expect("Failed to open inputs file");
    let inputs_reader = BufReader::new(inputs_file);
    let raw_inputs: serde_json::Value =
        serde_json::from_reader(inputs_reader).expect("Failed to read JSON inputs");
    let inputs: Vec<Gf2_128> = raw_inputs
        .as_array()
        .unwrap()
        .iter()
        .map(|v| parse_gf2_128(v.as_str().unwrap()))
        .collect();

    // 3. Generate Valid Proof
    let mut rng = SimpleRng::new(12345);
    let prover = ZkProver::new(circuit_data.clone(), config.clone());
    let commit = prover.commit(&inputs, &mut rng);
    let valid_proof = prover.prove(&inputs, &commit, "security_test");

    let verifier = ZkVerifier::new(circuit_data, config);
    let npublic_input = prover.circuit_data.npublic_input;
    let public_inputs = &inputs[0..npublic_input];

    // Verify original proof is indeed valid
    assert!(
        verifier
            .verify(public_inputs, &valid_proof, "security_test")
            .is_ok()
    );

    // Mutation A: Corrupt sumcheck layers length (DoS prevention check)
    {
        let mut mutated_proof = valid_proof.clone();
        mutated_proof.sumcheck_proof.truncate(1); // truncate layer count
        let res = verifier.verify(public_inputs, &mutated_proof, "security_test");
        assert!(
            res.is_err(),
            "Verifier should have rejected truncated layers proof instead of panicking!"
        );
    }

    // Mutation C: Corrupt req length (Malleability check)
    {
        let mut mutated_proof = valid_proof.clone();
        mutated_proof
            .ligero_proof
            .queried_columns
            .push(Gf2_128::zero()); // append extra element to query elements
        let res = verifier.verify(public_inputs, &mutated_proof, "security_test");
        assert!(
            res.is_err(),
            "Verifier should have rejected proof with wrong request size instead of validating it!"
        );
    }
}

#[test]
fn test_reference_rle_infinite_loop_prevention() {
    use reference::ligero::read_ligero_proof;

    let config = LigeroConfig::default();

    // 1. Create dummy circuit
    let circuit_file = File::open(get_testdata_path("tests/testdata/sha256_circuit.lfc2"))
        .expect("Failed to open circuit file");
    let mut circuit_reader = BufReader::new(circuit_file);
    let circuit =
        parse_lfc2_bytes::<Gf2_128, _>(&mut circuit_reader).expect("Failed to parse LFC2 circuit");

    let sf = <Gf2_128 as Field>::Subfield::default();

    let witness_only_len = circuit.ninput - circuit.npublic_input;
    let mut pad_witness_len = 3 * circuit.layers.len();
    for layer in &circuit.layers {
        pad_witness_len += 4 * layer.logw;
    }
    let nw = witness_only_len + pad_witness_len;
    let nq = circuit.layers.len();
    let geom = reference::ligero::LigeroGeometry::new(&config, nw, nq);

    let mut stream = Vec::new();
    for _ in 0..geom.block_len {
        stream.extend_from_slice(&[0u8; 16]);
    }
    for _ in 0..geom.dblock_len {
        stream.extend_from_slice(&[0u8; 16]);
    }
    for _ in 0..geom.num_queries {
        stream.extend_from_slice(&[0u8; 16]);
    }
    for _ in 0..(geom.dblock_len - geom.block_len) {
        stream.extend_from_slice(&[0u8; 16]);
    }
    for _ in 0..geom.num_queries {
        stream.extend_from_slice(&[0u8; 32]);
    }

    // First runlen = 0
    stream.extend_from_slice(&0u32.to_le_bytes());
    // Second runlen = 0 (MUST BE REJECTED)
    stream.extend_from_slice(&0u32.to_le_bytes());

    let mut cursor = Cursor::new(stream);
    let result = read_ligero_proof::<Gf2_128, _>(&mut cursor, &config, &circuit, &sf);
    assert!(
        result.is_err(),
        "Repeated runlen = 0 must be rejected to prevent infinite loop!"
    );
}

#[test]
fn test_computed_circuit_id_matches_stored() {
    let sha256_file = File::open(get_testdata_path("tests/testdata/sha256_circuit.lfc2")).unwrap();
    let mut sha256_reader = BufReader::new(sha256_file);
    let sha256_circuit = parse_lfc2_bytes::<Gf2_128, _>(&mut sha256_reader).unwrap();
    let computed_sha256_id = compute_circuit_id(&sha256_circuit);
    assert_eq!(
        sha256_circuit.id, computed_sha256_id,
        "SHA256 computed circuit ID does not match stored circuit ID"
    );

    let ecdsa2_file = File::open(get_testdata_path("tests/testdata/ecdsa2_circuit.lfc2")).unwrap();
    let mut ecdsa2_reader = BufReader::new(ecdsa2_file);
    let ecdsa2_circuit = parse_lfc2_bytes::<P256, _>(&mut ecdsa2_reader).unwrap();
    let computed_ecdsa2_id = compute_circuit_id(&ecdsa2_circuit);
    assert_eq!(
        ecdsa2_circuit.id, computed_ecdsa2_id,
        "ECDSA2 computed circuit ID does not match stored circuit ID"
    );
}
